apiVersion: v1
kind: Service
metadata:
  name: {{ include "smtpk.fullname" . }}-smtp4dev
  labels:
  {{- include "smtpk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.smtp4Dev.type }}
  selector:
    app: smtp4dev
  {{- include "smtpk.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.smtp4Dev.ports | toYaml | nindent 2 -}}